[MDBList]
api_key =
base_url = https://api.mdblist.com
timeout = 30

[Radarr]
url = http://localhost:7878
api_key =
mdblist_list_id =
mdblist_list_name = Radarr
mdblist_list_private = true

[Sonarr]
url = http://localhost:8989
api_key =
mdblist_list_id =
mdblist_list_name = Sonarr
mdblist_list_private = true
